<?php

function migracao_vozes_menu() {
  $items = array();

  $items['admin/settings/migracao_vozes'] = array(
    'title' => 'Migracao vozes',
    'description' => 'Import vozes da terra',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migracao_vozes_import_form'),
    'file' => 'migracao_vozes.pages.inc',
    'access arguments' => array('administer audio'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}