<?php
/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function nav_estruturada_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#nav_estruturada":
      $output = '<p>'.  t("Block for structured navigation.") .'</p>';
      break;
  }
  return $output;
} // function nav_estruturada_help


/**
* Valid permissions for this module
* @return array An array of valid permissions for the nav_estruturada module
*/

function nav_estruturada_perm() {
  return array('access relevant content');
} // function nav_estruturada_perm()


/**
* Generate HTML for the nav_estruturada block
* @param op the operation from the URL
* @param delta offset
* @returns block HTML
*/
function nav_estruturada_block($op='list', $delta=0) {
  // listing of blocks, such as on the admin/block page
  if ($op == "list") {
    $block[0]["info"] = t('Navegação estruturada');
    return $block;
  } else if ($op == 'view') {
    $block_content = _process_navigation();

    $block['subject'] = "Seções";
    $block['content'] = $block_content;
    return $block;
  }
} // end nav_estruturada_block

function _process_navigation() {
  
  // a partir do nid da pagina atual, descobre que tipo eh e que edicao
  $nid = arg(1);
  $resBookStat = db_query("SELECT b2.nid AS parent_nid, n.title AS parent_title, b3.nid AS edicao_nid,ml.p1,ml.p2,ml.p3 FROM node n, book b, book b2, book b3, menu_links ml WHERE ml.mlid = b.mlid AND b2.mlid = ml.p1 AND b3.mlid = ml.p2 AND n.nid = b2.nid AND b.nid = %d", $nid);
  $book = db_fetch_array($resBookStat);
  $menuSecoes = '';
  // se for revista ou jornal:
  if (in_array($book['parent_nid'], array(1,2))) {
    $resNavegacao = db_query(db_rewrite_sql("SELECT b.nid, td.name as secao FROM {menu_links} ml, {book} b, {book} b2, {term_data} td, {term_node} tn WHERE td.tid = tn.tid AND tn.nid = b.nid AND ml.mlid = b.mlid AND ml.p2 = b2.mlid AND b2.nid = %d"), $book['edicao_nid']);
    // pega resultado da navegacao
    $arrNavegacao = array();
    while($secaoNavegacao = db_fetch_array($resNavegacao)) {
      $secao = $secaoNavegacao['secao'];
      $arrNavegacao[$secao] = array('url' => 'node/' . $secaoNavegacao['nid']);
    }

    // define ordem e preenche o resto da navegacao (alem das categorias)
    if ($book['parent_title'] == 'Revista Sem Terra') {
	$arrOrder = array('Página Inicial'  => array('url' => 'node/' . $book['edicao_nid']),
			  'Destaque' => 'destaque', 
			  'Editorial' => 'editorial', 
			  'Reportagens' => 'reportagens', 
			  'Expediente' => 'expediente', 
			  'Assinaturas' => array('url' => 'assinaturas/revista'),
			  'Onde Comprar' => array('url' => 'onde_comprar'), 
			  'Fale Conosco' => array('url' => 'fale_conosco'),
			  'Edições da Revista' => array('url' => 'revistas'),
			  'Revista Sem-Terrinha' => 'Revista Sem-Terrinha'
			  );
    } 
    else if ($book['parent_title'] == 'Jornal Sem Terra') {
	$arrOrder = array('Página Inicial'  => array('url' => 'node/' . $book['edicao_nid']),
			  'Editorial' => 'editorial', 
			  'Destaque' => 'destaque', 
			  'Entrevista' => 'entrevista',
			  'Artigo' => 'artigo',
			  'Estados' => 'estados', 
			  'Internacional' => 'internacional', 
			  'Realidade Brasileira' => 'realidade brasileira', 
			  'Expediente' => 'expediente',
			  'Assinaturas' => array('url' => 'assinaturas/jornal'),
			  'Fale Conosco' => array('url' => 'fale_conosco'),
			  'Edições do Jornal' => array('url' => 'jornais'),
			  'Jornal Sem-Terrinha' => 'Jornal Sem-Terrinha'
			  );		
    }

    // mesclar termos, ordem etc
    $arrCompleto = array_merge_recursive($arrOrder, $arrNavegacao);
    //    print_r($arrCompleto);exit();
    $arrOrdenado = array();
    foreach ($arrOrder as $key => $value) {
	// prevent that a section without content to be linked
	if (is_array($arrCompleto[$key])) {
	    $arrOrdenado[$key] = $arrCompleto[$key];
	}
    }
    $arrNavegacao = $arrOrdenado;


    // cria HTML e formata
    $cssExtra = '';
    $cssExtra = " menu-revjorn";
    $menuSecoes = "<ul class='menu-revjorn'>";
    
    
    
    // somente se nao for capa, coloca capinha no menu
    if ("node/$nid" != $arrNavegacao['Página Inicial']['url']) {
	// imagem no topo
	$filterName = 'capa_revistajornal';
	$imagemCapa = db_result(db_query("SELECT f.filepath FROM {files} f, {content_type_book} ctb WHERE f.fid = ctb.field_capa_fid AND ctb.nid = %d", $book['edicao_nid']));
	
	if ($imagemCapa != '') {
	    $imagemCapa = preg_replace('/(.*)\/images\/(.*)/',
				       "$1/imagecache/$filterName/images/$2",
				       $imagemCapa);
	    $menuSecoes .= "<li class='menu-revjorn'><img width='123' height='164' src='" . url($imagemCapa) . "'></li>";
	}
    }
    
    foreach ($arrNavegacao as $chave => $secao) {
      $url = $secao['url'];
      
      if ($chave == 'Jornal Sem-Terrinha' || $chave == 'Revista Sem Terrinha') {
	  $tidSemTerrinha = db_result(db_query("SELECT tid FROM {term_data} WHERE name like '$chave'"));
	  $img_src = db_result(db_query("SELECT f.filepath FROM {files} f, {content_type_book} ctb, {content_type_book} ctb2, {menu_links} ml, {book} b, {book} b2, {term_node} tn WHERE f.fid = ctb.field_capa_fid AND ctb.nid = tn.nid AND tn.tid=%d AND b.nid = ctb.nid AND b.mlid = ml.mlid      AND ml.p2 = b2.mlid AND b2.nid = ctb2.nid AND ctb2.nid = %d", $tidSemTerrinha, $book['edicao_nid']));
	  if ($img_src != "") {
	      $menuSecoes .= "<li><a style='border=\"0\"' href='". url($url) ." '>". $chave ."<img width=130px; src='" . url($img_src) . "'></a><br/></li>";
	  }
      } else {
        $menuSecoes .= "<li><a href='". url($url) ." '>". $chave ."</a></li>";
      }
    }
    $menuSecoes .= "</ul>";
  }
  
  return $menuSecoes;
}

